project_id = "sibdsejxpjgdlpdzcgej"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.create-influencer]
verify_jwt = true

[functions.create-pix]
verify_jwt = true

[functions.woovi-webhook]
verify_jwt = false

[functions.woovi-webhook-expired]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MB"