// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sibdsejxpjgdlpdzcgej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpYmRzZWp4cGpnZGxwZHpjZ2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTc4MTksImV4cCI6MjA3MjMzMzgxOX0.bVt_mFhBTpPtHQbLWoHSiUn7VsL5Zk14ncuXig9q-TA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});